name: Build & Push to Docker Hub

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Kumuha ng mga file
        uses: actions/checkout@v4

      - name: 🔑 Mag-login sa Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_virgozki }}
          password: ${{ secrets.DOCKER_dckr_pat_bI23fAx1dX9XcJ9nOxphpl6HW_k }}

      - name: 🛠️ I-build at i-push ang image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: virgozki/rafaelragos:latest
